### ISSUE TITLE
Existence of pylonsrtd is confusing

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pylonsrtd#44]
http://www.pylonsproject.org/ should present the organization of the Pylons Project and each of its projects' metadata.

Currently https://github.com/Pylons/pylonsrtd (rendered at http://docs.pylonsproject.org/en/latest/) and https://github.com/Pylons/pylonshq (rendered at http://www.pylonsproject.org/) is confusing, and lacks purpose and focus. The Pylons Project itself should not have any documentation. Each of its projects should have their own documentation.

I propose merging content from pylonsrtd and pylonshq into a new repo https://github.com/Pylons/pylonsprojectorg so that we satisfy the following goals.
1. Don't depend on Sphinx and RTD to build the marketing site for the PP organization.
2. Have a single place to edit the marketing site for the PP organization.
3. Use a distinguishing name for the repository that is associated to its URL.

**Comment by blaflamme** [comment]
In fact it's the opposite

https://github.com/Pylons/pylonsrtd -> http://docs.pylonsproject.org/en/latest/
https://github.com/Pylons/pylonshq -> http://www.pylonsproject.org/

FYI pylonsrtd was originally created as an entry point on RTD for all our projects docs and pylonshq was created in a hurry before @mcdonc and @bbangert did a podcast interview to have a minimal website, and it was before we moved over RTD for hosting the docs.

**Comment by stevepiercy** [comment]
Made edits to above.

**Comment by blaflamme** [comment]
ppo repo created+ marketing team with initial people involved

**Comment by stevepiercy** [comment]
@blaflamme could you rename it to pylonsprojectorg?

**Comment by stevepiercy** [comment]
Closing in favor of #65
