### ISSUE TITLE
rename this repo to docs.pylonsproject.org

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pylonsrtd#60]
Pretty please? It's impossible to find every time I need to change it. It's probably not discoverable for anyone else either.

**Comment by stevepiercy** [comment]
There's an open issue #2 that addresses this matter, but from a broader perspective.

**Comment by mmerickel** [comment]
You linked to the wrong thing. Not sure what you intended.

**Comment by stevepiercy** [comment]
Oops, this one #44.

**Comment by mmerickel** [comment]
Okay, I agree with that issue of course but it's over 1 year later. Any objecttions if I just rename this repo in the short term?

**Comment by stevepiercy** [comment]
Yes, primary objection is then links to this repo from other projects will need to be updated to avoid 404s, I'd need to change my local repos, and so on.

I'd much rather prefer a better description of the repo than a rename of the repo.

**Comment by mmerickel** [comment]
Github will automatically redirect all old links to new ones.

https://help.github.com/articles/renaming-a-repository/

**Comment by blaflamme** [comment]
docs.pylonsproject.org will at least reflects what this repos is for until a major refactoring is done, and that would take a good amount of effort.

**Comment by blaflamme** [comment]
but we'll have to reconfigure some stuff on rtd to make sure docs.pylonsproject.org points out to the right repo.

**Comment by stevepiercy** [comment]
The name `docs.pylonsproject.org` would add to the confusion because every project documented under the Pylons Project has `docs.pylonsproject.org` as part of its canonical URL:

http://docs.pylonsproject.org/projects/pyramid/en/latest/

This repo is already deprecated, and will be removed when we launch https://pylonsproject.org

**Comment by blaflamme** [comment]
at the moment `pylonsrtd` is providing `docs.pylonsproject.org` content, all other projects are under `/projects` namespace, so it makes sense to have it renamed to `docs.pylonsproject.org` if it helps contributor contribute more.

I agree that some of the content would be moved over the new `pylonsproject.org` repo but `docs.pylonsproject.org` will still need to have an entry page, or project, that would be rendered by `readthedocs.org`, this is how it works. This repo will then still exists in a refactored way when the new pylonsproject.org` will be done.

**Comment by mmerickel** [comment]
>  This repo will then still exists in a refactored way when the new pylonsproject.org will be done.

I agree, knowing how rtd works, I don't see how we can drop this repo wholesale unless we want `docs.pylonsproject.org` to be a 404. That domain is a CNAME to rtd in order to allow it to do all of the project mappings.

**Comment by stevepiercy** [comment]
It should be a 404 in the future.

Why would we want to maintain the same information in two places, at https://pylonsproject.org and at http://docs.pylonsproject.org/en/latest/ ?

**Comment by mmerickel** [comment]
No one is saying to maintain the same information but a 404 is not an acceptable answer. We will at least leave a page pointing people at pylonsproject.org. We can even setup rtd to redirect automatically, but only if we have a project there in the first place.

**Comment by stevepiercy** [comment]
`docs.pylonsproject.org` only is ambiguous. If this repo will be renamed, then let's be explicit with its name: `docs.pylonsproject.org_rtd_index_only`, `docs.pylonsproject.org_index_only`, or`docs.pylonsproject.org_deprecated`. Of course, that would still not accurately reflect the current state of this repo.

Let's just let sleeping dogs lie.

**Comment by mmerickel** [comment]
Again, deprecated is not the right word here.

I concede. I don't want to ruffle your feathers.

**Comment by stevepiercy** [comment]
/me smoothes feathers. 😛 

Nonetheless, a point raised in this issue should be a separate issue, so I would like to capture that before closing this issue.

@blaflamme suggested an entry page or project, but @mmerickel suggested a redirect. I lean toward a redirect to avoid the temptation of duplicating content.

If a decision can be reached, then I'll create an issue for that.

**Comment by blaflamme** [comment]
My point was that we need to keep the repo to make RTD works independently of what we put there, and it can’t be 404.

**Comment by stevepiercy** [comment]
@blaflamme so what should it be: entry page, project, or redirect?

**Comment by blaflamme** [comment]
Can’t say now as nothing is done for next pylonsproject.org <http://pylonsproject.org/>. Any of those is a good contender I think, will depends on what's best when we'll be there. What’s important I think is to be aware we still need a repo for docs.pylonsproject.org <http://docs.pylonsproject.org/> to work on RTD.
